# Site settings
title: yuriyczoli

email: yuriy.czoli@gmail.com

description: Geo-Jabberwocky

host: localhost

port: 8009

sass:
  style: :compressed

highlighter: rouge

collections:
  projects:
    output: true
    permalink: /projects/:path/

baseurl: "" # the subpath of your site, e.g. /blog/

# Build settings

markdown: kramdown
